export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { options } = req.body;

    let htaccess = '# Generated by Htaccess Generator Pro\\n';
    htaccess += '# Generated: ' + new Date().toISOString() + '\\n\\n';

    // SEO Rewrite Rules
    if (options?.rewrite) {
      htaccess += '# SEO Rewrite Rules\\n';
      htaccess += '<IfModule mod_rewrite.c>\\n';
      htaccess += 'RewriteEngine On\\n';
      htaccess += 'RewriteBase /\\n\\n';
      htaccess += '# Remove .php extension\\n';
      htaccess += 'RewriteCond %{REQUEST_FILENAME} !-d\\n';
      htaccess += 'RewriteCond %{REQUEST_FILENAME}.php -f\\n';
      htaccess += 'RewriteRule ^([^/]+)/?$ $1.php [L]\\n\\n';
      htaccess += '# Redirect to HTTPS\\n';
      htaccess += 'RewriteCond %{HTTPS} off\\n';
      htaccess += 'RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]\\n';
      htaccess += '</IfModule>\\n\\n';
    }

    // Security Headers
    if (options?.security) {
      htaccess += '# Security Headers\\n';
      htaccess += '<IfModule mod_headers.c>\\n';
      htaccess += 'Header always set X-Frame-Options "SAMEORIGIN"\\n';
      htaccess += 'Header always set X-Content-Type-Options "nosniff"\\n';
      htaccess += 'Header always set X-XSS-Protection "1; mode=block"\\n';
      htaccess += 'Header always set Referrer-Policy "strict-origin-when-cross-origin"\\n';
      htaccess += 'Header always set Permissions-Policy "geolocation=(), microphone=(), camera=()"\\n';
      htaccess += '</IfModule>\\n\\n';
    }

    // Browser Caching
    if (options?.cache) {
      htaccess += '# Browser Caching\\n';
      htaccess += '<IfModule mod_expires.c>\\n';
      htaccess += 'ExpiresActive On\\n';
      htaccess += 'ExpiresByType image/jpeg "access plus 1 year"\\n';
      htaccess += 'ExpiresByType image/png "access plus 1 year"\\n';
      htaccess += 'ExpiresByType image/webp "access plus 1 year"\\n';
      htaccess += 'ExpiresByType text/css "access plus 1 month"\\n';
      htaccess += 'ExpiresByType application/javascript "access plus 1 month"\\n';
      htaccess += '</IfModule>\\n\\n';
    }

    // Gzip Compression
    if (options?.gzip) {
      htaccess += '# Gzip Compression\\n';
      htaccess += '<IfModule mod_deflate.c>\\n';
      htaccess += 'AddOutputFilterByType DEFLATE text/html text/plain text/css application/javascript application/json\\n';
      htaccess += '</IfModule>\\n\\n';
    }

    // Hotlink Protection
    if (options?.hotlink) {
      htaccess += '# Hotlink Protection\\n';
      htaccess += '<IfModule mod_rewrite.c>\\n';
      htaccess += 'RewriteEngine On\\n';
      htaccess += 'RewriteCond %{HTTP_REFERER} !^$\\n';
      htaccess += 'RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?yourdomain.com [NC]\\n';
      htaccess += 'RewriteRule \\.(jpg|jpeg|png|gif|webp)$ - [F,NC]\\n';
      htaccess += '</IfModule>\\n\\n';
    }

    return res.status(200).json({
      success: true,
      htaccess,
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    return res.status(500).json({
      error: 'Failed to generate htaccess',
      message: error.message
    });
  }
}
